<?php

namespace ADIF\PortalProveedoresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoNotificacionRepository extends EntityRepository
{
}