<?php

namespace ADIF\PortalProveedoresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProveedorUteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorUteRepository extends EntityRepository
{
}
