<?php

namespace ADIF\PortalProveedoresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProveedorUteMiembrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorUteMiembrosRepository extends EntityRepository
{
}
