<?php

namespace ADIF\PortalProveedoresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTimelineRepository extends EntityRepository
{
}
