<?php

namespace ADIF\PortalProveedoresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{

    /**
     *
     * @return AllDetalle
     */
    public function getAllWithStatus() {
        
        $sql = '
            select 
                inv.id, 
                inv.email, 
                pro.cuit, 
                inv.fecha_alta, 
                usu.last_login, 
                IF (isnull(usu.email), IF((inv.enviado = 0),"Interesado", "Pendiente") , "Registrado") as estado 
            from adif_proveedores.invitacion inv 
            left join  adif_proveedores.usuario usu on (inv.email = usu.email)
            left join  adif_proveedores.proveedor_dato_personal pro on (inv.email = pro.email)';

        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();

    }

}







