<?php

namespace ADIF\PortalProveedoresBundle\Repository;

/**
 * VisitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     *
     * @param {datetime} $desde
     * @param {datetime} $hasta
     * @param {bolean} $busquedaEstrictaPorUser
     * @return array
     */
    public function getVisitasPorFecha($desde = null, $hasta = null, $busquedaEstrictaPorUser) {
        $format = "d/m/Y";
        $desde = \DateTime::createFromFormat($format, $desde);
        $hasta = \DateTime::createFromFormat($format, $hasta);

        $desde = $desde->format("Y-m-d");
        $hasta = $hasta->format("Y-m-d");

        $sql = "SELECT date( v.fecha) AS gFecha, Count(*) AS cantidad FROM adif_proveedores.visitas v WHERE fecha BETWEEN :desde AND :hasta GROUP BY gFecha";

        if($busquedaEstrictaPorUser == 'true')
            $sql = "SELECT date( v.fecha) AS gFecha, Count(distinct(id_usuario)) AS cantidad FROM adif_proveedores.visitas v WHERE fecha BETWEEN :desde AND :hasta GROUP BY gFecha";

        $em = $this->getEntityManager();

        $stmt = $em->getConnection()->prepare($sql);
        $stmt->bindValue('desde', $desde);
        $stmt->bindValue('hasta', $hasta . ' 23:59:59');
        $stmt->execute();
        return $stmt->fetchAll();

    }

    /**
     *
     * @param {datetime} $desde
     * @param {datetime} $hasta
     * @param {bolean} $busquedaEstrictaPorUser
     * @return array
     */
    public function getVisitasPorHora($desde = null, $hasta = null, $busquedaEstrictaPorUser)
    {

        $format = "d/m/Y";
        $desde = \DateTime::createFromFormat($format, $desde);
        $hasta = \DateTime::createFromFormat($format, $hasta);

        $desde = $desde->format("Y-m-d");
        $hasta = $hasta->format("Y-m-d");

        $sql = "SELECT date(v.fecha) AS gFecha, hour(v.fecha) AS gHora, Count(*) AS cantidad FROM adif_proveedores.visitas v
            WHERE fecha BETWEEN :desde AND :hasta GROUP BY gFecha, gHora";

        if($busquedaEstrictaPorUser === 'true')
            $sql = "SELECT date(v.fecha) AS gFecha,hour(v.fecha) AS gHora, Count(distinct(id_usuario)) AS cantidad FROM adif_proveedores.visitas v
            WHERE fecha BETWEEN :desde AND :hasta GROUP BY gFecha, gHora";

        $em = $this->getEntityManager();

        $stmt = $em->getConnection()->prepare($sql);
        if (!empty($desde)) $stmt->bindValue('desde', $desde);
        if (!empty($hasta)) $stmt->bindValue('hasta', $hasta . ' 23:59:59');
        $stmt->execute();
        return $stmt->fetchAll();

    }
}
