INSERT INTO adif_proveedores.tipo_documentacion (id, denominacion) VALUES
(1, 'proveedor_actividad'),
(2, 'proveedor_rubro'),
(3, 'proveedor_domicilio_legal'),
(4, 'proveedor_domicilio_fiscal'),
(5, 'proveedor_domicilio_contraactual'),
(6, 'proveedor_representante_apoderado'),
(7, 'proveedor_datos_impositivos'),
(8, 'proveedor_datos_impositivos_iva'),
(9, 'proveedor_datos_impositivos_suss'),
(10, 'proveedor_datos_impositivos_ganancias'),
(11, 'proveedor_datos_impositivos_iibb'),
(12, 'proveedor_datos_impositivos_constancia_inscripcion'),
(13, 'proveedor_datos_bancarios'),
(14, 'proveedor_datos_bancarios_cbu'),
(15, 'proveedor_gcshm'),
(16, 'proveedor_ute_miembros'),
(17, 'proveedor_persona_juridica');


INSERT INTO adif_proveedores.tipo_observacion (id, denominacion) VALUES
(1, 'proveedor_dato_personal'),
(2, 'proveedor_dato_contacto'),
(3, 'proveedor_persona_juridica'),
(4, 'proveedor_ute'),
(5, 'proveedor_ute_miembros'),
(6, 'proveedor_actividad'),
(7, 'proveedor_rubro'),
(8, 'proveedor_domicilio_legal'),
(9, 'proveedor_domicilio_fiscal'),
(10, 'proveedor_domicilio_contraactual'),
(11, 'proveedor_representante_apoderado'),
(12, 'proveedor_datos_impositivos'),
(13, 'proveedor_datos_impositivos_iva'),
(14, 'proveedor_datos_impositivos_suss'),
(15, 'proveedor_datos_impositivos_ganancias'),
(16, 'proveedor_datos_impositivos_iibb'),
(17, 'proveedor_datos_impositivos_constancia_inscripcion'),
(18, 'proveedor_datos_bancarios'),
(19, 'proveedor_datos_bancarios_cbu'),
(20, 'proveedor_gcshm');