# Doctrine Configuration
doctrine:
    dbal:
        default_connection: siga_autenticacion
        connections:
            siga_autenticacion:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name_autenticacion%"
                user:     "%database_adif_user%"
                password: "%database_adif_password%"
                charset:  UTF8
                mapping_types:
                  enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: siga_autenticacion
        entity_managers:
            siga_autenticacion:
                connection: siga_autenticacion
                mappings:
                    ADIFAutenticacionBundle: ~
